### PR TITLE
changed folder structure and added new test notebook

### PR DESCRIPTION
**Pull request by paltube**
In this pull request there's a new notebook "DealiasedBins.ipynb"; please have a look at it.
I'm doing a mess with this, I'm aware. But I'm learning a bit. Now I see I should do commits step by step.

### CODE REVIEW

**Comment by scollis** [comment]
All good! Learning is good. You should have seen the mess I made when learning. @jjhelmus can you merge this pr please

**Comment by scollis** [comment]
I will say though, we need to find some where else for the data.. Should not have data in the repository. We can use figshare for that

**Comment by jjhelmus** [comment]
FYI, you need to divide by 2 \* Ny_vel to get the number of Nyquist intervals applied during dealiasing.

**Comment by paltube** [comment]
Thanks Jonathan, I'll fix that. 
I think I need some guidelines about what (not) to put in the repository, appropriate folder structure and general info for proper use. :)

**Comment by jjhelmus** [comment]
The folder structure and layout depends on the project, you can rename and move files/folders using `git mv` if needed.  As for what to include, I suggest all scripts/notebooks/etc that produce meaningful results.    Intermediate files and large data files should not be included.

**Pull request merged**
