### PR TITLE
added SMC network info in project_plans.md

### PR DESCRIPTION
**Pull request by paltube**

### CODE REVIEW

**Comment by scollis** [comment]
Thanks @Patri-meteocat

**Comment by jjhelmus** [comment]
Typically it is not a good idea to keep temporary files in the  .ipynb_checkpoints directory under version control.  If you add the directory to a `.gitignore` file they will not be shown in `git status` messages or added using `git commit -a`.

**Comment by scollis** [comment]
Good point.. And we briefly talked about branching as well.. I told @Patri-meteocat my method of pulling into upstream then git pull upstream master into local.

**Comment by paltube** [comment]
Yes, thank you both; forgot that I had the notebooks directory inside. I'll edit `.gitignore` file. Best way to hide/delete `.ipynb_checkpoints` directory from EVS-ATMOS/Meteocat_ANL_collaboration?

**Pull request merged**
